Improve validated accessor definition
- Fix documentation
- Use a heredoc to define a multi-line string, which makes the code
  easier to understand at a glance.
- Error Handling: If there's an error in the method definition, it will
  be easier to debug because the error message will point to the exact
  line of code where the error occurred.
- Provide a comment block showing the aspect of an interpolated method
  https://rubystyle.guide/#eval-comment-docs

Old approach:
```
Error: test_add_selection(TestSheetView): RuntimeError: Hello
~/dev/caxlsx/lib/axlsx/util/accessors.rb:59:in `right_to_left='

--> module_eval(format(SETTER, symbol, validator, symbol), __FILE__, __LINE__)
```


New approach:
```
Error: test_to_xml(TestSheetView): RuntimeError: Hello
~/dev/caxlsx/lib/axlsx/util/accessors.rb:58:in `right_to_left='

    module_eval <<-RUBY_EVAL, __FILE__, __LINE__ + 1
      def #{symbol}=(value)      # def name=(value)
-->     raise 'Hello'
        Axlsx.#{validator} value #   Axlsx.validate_string value
        @#{symbol} = value       #   @name = value
      end                        # end
    RUBY_EVAL
```